import react from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ChakraProvider } from "@chakra-ui/react"
import Header from '../src/Components/Header'

const Home: NextPage = () => {
  return (
    <ChakraProvider>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </ChakraProvider>
  )
}

export default Home